
  
    const QUESTIONS = [{
      "question": "What is the primary feature of a passive thermal control system in a spacecraft?",
      "options": {
        "A": "It requires external power for operation.",
        "B": "It uses active components with relative movement.",
        "C": "It eliminates the possibility of failure by avoiding moving parts and external power.",
        "D": "It relies entirely on heat generated by spacecraft systems."
      },
      "correct_answer": "C"
    },
    {
      "question": "How is heat rejected in the passive thermal control of spacecraft?",
      "options": {
        "A": "Heat is conducted through thermal pipelines.",
        "B": "Heat is rejected through Optical Solar Reflectors (OSR).",
        "C": "Heat is absorbed by high-energy radiators.",
        "D": "Heat is managed using power-driven cooling systems."
      },
      "correct_answer": "B"
    },
    {
      "question": "What properties are utilized in passive thermal control systems for spacecraft?",
      "options": {
        "A": "Aerodynamic properties of components.",
        "B": "Thermo-optical properties of components.",
        "C": "Thermal expansion properties of materials.",
        "D": "Elastic properties of materials."
      },
      "correct_answer": "B"
    }
  ,
  
    {
      "question": "What is one common application of Chemical Vapour Deposition (CVD)?",
      "options": {
        "A": "Depositing metals, dielectrics, and other compounds.",
        "B": "Erosion testing of surface materials.",
        "C": "Creating mechanical joints in large structures.",
        "D": "Polishing surfaces for enhanced reflectivity."
      },
      "correct_answer": "A"
    },
    {
      "question": "Which of the following materials can be deposited using Chemical Vapour Deposition (CVD)?",
      "options": {
        "A": "Plastics and wood composites.",
        "B": "Polysilicon and dielectrics.",
        "C": "Glass and ceramics.",
        "D": "Organic liquid compounds."
      },
      "correct_answer": "B"
    }
  ,
  
    {
      "question": "What is the purpose of surface engineering technologies?",
      "options": {
        "A": "To analyze the chemical composition of compounds.",
        "B": "To deposit metals, dielectrics, polysilicon, and other compounds.",
        "C": "To extract materials from surfaces for study.",
        "D": "To polish and clean metallic surfaces."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which materials can surface engineering technologies deposit?",
      "options": {
        "A": "Only metals and ceramics",
        "B": "Only dielectrics and semiconductors",
        "C": "Metals, dielectrics, polysilicon, and other compounds",
        "D": "Gases and liquids exclusively"
      },
      "correct_answer": "C"
    }
  ,
  
    {
      "question": "What is the main purpose of black anodizing in surface engineering technologies?",
      "options": {
        "A": "To increase the thickness of a surface layer.",
        "B": "To achieve a flat absorbing surface.",
        "C": "To improve the conductivity of the material.",
        "D": "To decrease surface friction."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which chemical reaction occurs during the process of black anodizing using inorganic coloring?",
      "options": {
        "A": "The formation of cobalt acetate in the surface pores.",
        "B": "The precipitation of cobalt sulfide in the coating pores.",
        "C": "The reaction between ammonium sulfide and aluminum.",
        "D": "The decomposition of anodic coatings into carbon dioxide."
      },
      "correct_answer": "B"
    },
    {
      "question": "What is the result of the black anodizing process in terms of emittance value?",
      "options": {
        "A": "0.50",
        "B": "0.75",
        "C": "0.91",
        "D": "1.00"
      },
      "correct_answer": "C"
    }
  ,
  
    {
      "question": "Why is magnesium considered a difficult finishing metal?",
      "options": {
        "A": "Due to its low density.",
        "B": "Because of its high reactivity and position in the EMF series.",
        "C": "Owing to its non-reactive surface.",
        "D": "Because it does not conduct electricity efficiently."
      },
      "correct_answer": "B"
    },
    {
      "question": "What issue arises due to the softness of magnesium during mechanical operations?",
      "options": {
        "A": "Formation of a brittle layer on the surface.",
        "B": "Increased electrical conductivity.",
        "C": "Inclusion of harder material particles causing electro-chemical heterogeneity.",
        "D": "A uniform distribution of material particles across the surface."
      },
      "correct_answer": "C"
    },
    {
      "question": "Which of the following is a surface engineering technology mentioned for magnesium alloys?",
      "options": {
        "A": "Electroplating",
        "B": "Micro Arc Oxidation",
        "C": "Laser Ablation",
        "D": "Cold Spraying"
      },
      "correct_answer": "B"
    }
  ,
  
    {
      "question": "What is the primary purpose of a primer in the context of thermal control paints?",
      "options": {
        "A": "To add a decorative layer on the surface.",
        "B": "To enhance the adhesion of paint to the surface.",
        "C": "To increase the thermal conductivity of the surface.",
        "D": "To reduce the curing time of the paint."
      },
      "correct_answer": "B"
    },
    {
      "question": "What is the usual temperature range for vacuum baking applied to thermal control paints?",
      "options": {
        "A": "0-10˚C",
        "B": "30-40˚C",
        "C": "50-60˚C",
        "D": "100-110˚C"
      },
      "correct_answer": "C"
    },
    {
      "question": "What is the main component in pigments used in thermal control paints?",
      "options": {
        "A": "Organic dyes",
        "B": "Inorganic metal salts",
        "C": "Synthetic polymers",
        "D": "Natural plant extracts"
      },
      "correct_answer": "B"
    }
  ,
  
    {
      "question": "What is a primary feature of the HVOF (High Velocity Oxy-Fuel) spraying process?",
      "options": {
        "A": "It produces thick and uneven coatings.",
        "B": "It creates thin, strong, and corrosion-resistant coatings.",
        "C": "It only works effectively at very high temperatures.",
        "D": "It uses a cold stream of air instead of a gas stream."
      },
      "correct_answer": "B"
    },
    {
      "question": "What role does the torch play in the HVOF spraying process?",
      "options": {
        "A": "It heats the surface for better coating adherence.",
        "B": "It allows the flame to spread and accelerates the particles.",
        "C": "It creates high vacuum pressure for the coating process.",
        "D": "It solidifies the coating after application."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which fuel gases can be used in the HVOF process?",
      "options": {
        "A": "Only hydrogen and acetylene.",
        "B": "Only natural gas and propane.",
        "C": "Hydrogen, propylene, acetylene, natural gas, and propane.",
        "D": "Oxygen is the only fuel gas required."
      },
      "correct_answer": "C"
    },
    {
      "question": "What makes HVOF coatings resist corrosion better than plasma coatings?",
      "options": {
        "A": "Their thick application.",
        "B": "Uniform and strong adherence of the thin coat.",
        "C": "High compatibility with extremely high temperatures.",
        "D": "Use of hydrogen gas in the process."
      },
      "correct_answer": "B"
    },
    {
      "question": "Why is HVOF not suited for high-temperature applications?",
      "options": {
        "A": "It produces a weak coating under high heat.",
        "B": "Its thin coating layer cannot withstand extreme temperatures.",
        "C": "Its ignition process is unstable at high temperatures.",
        "D": "It uses non-flammable gases that degrade in heat."
      },
      "correct_answer": "B"
    }
  ,
  
    {
      "question": "What is the primary purpose of a diffuser plate in thermal control systems?",
      "options": {
        "A": "To generate heat in a system.",
        "B": "To distribute heat evenly across surfaces.",
        "C": "To insulate against external temperatures.",
        "D": "To cool the system by radiation dispersion."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which material is commonly used for diffuser plates in thermal control?",
      "options": {
        "A": "Plastic",
        "B": "Glass",
        "C": "Aluminium or copper",
        "D": "Carbon fiber"
      },
      "correct_answer": "C"
    },
    {
      "question": "What is the function of an MLI (Multi-Layer Insulation) blanket in thermal control?",
      "options": {
        "A": "To prevent radiation heat loss.",
        "B": "To allow faster heat transfer.",
        "C": "To act as a structural support.",
        "D": "To convert heat into electricity."
      },
      "correct_answer": "A"
    }
  ,
  
    {
      "question": "What is the primary purpose of thermal interface materials in spacecraft components?",
      "options": {
        "A": "To insulate electronic packages from external heat.",
        "B": "To enhance heat transfer from electronic packages to mounting surfaces.",
        "C": "To generate additional thermal energy during spacecraft operation.",
        "D": "To prevent electronic packages from functioning at high temperatures."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which of the following is a type of thermal interface material used in spacecraft?",
      "options": {
        "A": "Carbon fiber sheet",
        "B": "Silicone foam",
        "C": "Graphite foil",
        "D": "Ceramic insulator"
      },
      "correct_answer": "C"
    },
    {
      "question": "What is the function of thermal grease in spacecraft thermal control?",
      "options": {
        "A": "To provide electrical insulation.",
        "B": "To dissipate energy into the atmosphere.",
        "C": "To improve thermal contact conductance.",
        "D": "To protect components from mechanical stress."
      },
      "correct_answer": "C"
    }
  ,
  
    {
      "question": "What is the primary function of the PGS thermal strap?",
      "options": {
        "A": "Heat insulation in spacecraft components.",
        "B": "A passive thermal conduction heat transport element.",
        "C": "An active cooling device with inbuilt fans.",
        "D": "A structure for mechanical load transfer."
      },
      "correct_answer": "B"
    },
    {
      "question": "Which of the following is NOT a feature of the PGS thermal strap?",
      "options": {
        "A": "It can damp vibrations.",
        "B": "It tolerates dimensional mismatches.",
        "C": "It transfers heat actively using electrical power.",
        "D": "It can work within a temperature range of -150 to 250℃."
      },
      "correct_answer": "C"
    },
    {
      "question": "What is a limitation of the PGS thermal strap?",
      "options": {
        "A": "Its low in-plane thermal conductance.",
        "B": "Incompatibility with high-capacity heat transfer.",
        "C": "Heat transfer across longer distances.",
        "D": "Inability to connect between different planes."
      },
      "correct_answer": "C"
    }
  ]
